config/routes.rb
Rails.application.routes.draw do
  get 'usuarios/new'
  #get 'welcome/index'
  resources :images
  resources :usuarios
  root :to => "welcome#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/usuario.rb
class Usuario < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  def new
  end

  def create
    @usuario = Usuario.new usuario_params
    @usuario.save
  end
  
  def index
    @allUsuarios = Usuario.all
  end

  def edit
     @usuario = Usuario.find(params[:id])
  end

  private
     def usuario_params
         params.require(:usuario).permit(:nombre, :apellido, :correo)
     end 
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mynewprojects</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/usuarios/index.html.erb
<h1>Lista de usuarios</h1>

<%= link_to 'nuevo usuario', new_usuario_path %>
<br><br><br>

<table>
<tr>
<th>Nombre</th>
<th>Apellido</th>
<th>Correo</th>
<th>Editar</th>
</tr>
<% @allUsuarios.each do |f| %>
<tr>
<td><%= f.nombre %></td>
<td><%= f.apellido %></td>
<td><%= f.correo %></td>
<td><%= link_to 'editar', edit_usuarios_path(f) %></td>
</tr>
<% end %>
</table>

app/views/usuarios/new.html.erb
<h1>Creador de usuarios</h1>
<%= form_for :usuario, url: usuarios_path do |f| %>
    <p><%= f.label :nombre%>
    <%= f.text_field :nombre%><br>
    </p>
    <p>
    <%= f.label :apellido%>
    <%= f.text_field :apellido%><br>
    </p>
    <p>
    <%= f.label :correo%>
    <%= f.text_field :correo%><br>
    </p>
    <%= f.submit %>
 <% end %>   

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<h2>Hola Mundo</h2>
<p>Find me in app/views/welcome/index.html.erb</p>